import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Space+Mono:wght@400;700&display=swap"
        />
      </head>
      <body
        className="min-h-full flex flex-col"
        style={{
          backgroundColor: "#0a0a0a",
          color: "#f5f5f5",
          fontFamily: "'Space Grotesk', sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
